name: Delete Docker Containers

on:
  delete:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  delete-docker-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
        shell: bash

      - name: List package versions
        id: list-packages
        uses: gr2m/get-all-package-versions-action@v1.x
        with:
          registry: ghcr.io
          package: '${{ github.repository_owner }}/${{ github.repository_name }}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Docker packages
        if: steps.list-packages.outputs.versions
        run: |
          for tag in ${{ steps.list-packages.outputs.versions }}; do
            curl -X DELETE \
              -H "Accept: application/vnd.github.package-deletes-preview+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/packages/container/${{ github.repository_owner }}/${{ github.repository_name }}:${tag}"
          done