name: Delete Docker Containers

on:
  delete:
    branches:
      - 'feature/*'
      - 'hotfix/*'
  workflow_dispatch:

jobs:
  delete-docker-containers:
    runs-on: ubuntu-latest
    steps:
      - name: List all packages
        id: list-packages
        run: |
          curl \
            -H "Accept: application/vnd.github.package-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/packages/container/${{ github.repository_owner }}/${{ github.repository_name }}/versions" \
            > packages.json
          echo "::set-output name=packages::$(cat packages.json)"

      - name: Delete Docker packages
        if: steps.list-packages.outputs.packages
        run: |
          for pkg in ${{ steps.list-packages.outputs.packages }}; do
            if echo "$pkg" | jq -e ".metadata.container.tags | index(\"${{ github.ref_name }}\")" > /dev/null; then
              package_id=$(echo "$pkg" | jq -r ".id")
              curl -X DELETE \
                -H "Accept: application/vnd.github.package-deletes-preview+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/packages/container/${{ github.repository_owner }}/${{ github.repository_name }}/versions/$package_id"
            fi
          done