# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write



jobs:
  build-test:
    name: Build & Test Solution
    uses: ftoft/shared-workflows/.github/workflows/dotnet-test.yml@main
    with:
      PROJECT_PATH: "./src"

  build-docker-containers:
    name: Build Docker Containers
    needs: build-test
    
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./src/DotnetSamlpe.Docker/Dockerfile
            image_name: dotnet-sample
          - dockerfile: ./src/DotnetSample.DockerAwesome/Dockerfile
            image_name: dotnet-sample-awesome
    
    uses: ftoft/shared-workflows/.github/workflows/dotnet-build-test-publish-docker.yml@main
    with:
      PROJECT_PATH: "./src"
      DOCKERFILE_PATH: ${{ matrix.dockerfile }}
      DOCKER_CONTAINER_NAME: ${{ matrix.image_name }}
    secrets:
      token: ${{ secrets.token }}
