# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: "./src"
  DOCKERFILE: "./src/DotnetSamlpe.Docker/Dockerfile"

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: Build Solution
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release
    
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} -c Release --verbosity normal --logger "trx;logfilename=testResults.trx"
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/TestResults/*.trx
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Docker Images
      if: ${{ success() }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.PROJECT_PATH }}  
        push: true
        tags: |
          ${{ github.repository_owner }}/dotnet-sample:latest
        file: ${{ env.DOCKERFILE }}
