# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - 'main'
      - 'development'
      - 'feature/*'
      - 'hotfix/*'
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build-test:
    name: Build & Test Solution
    uses: ftoft/shared-workflows/.github/workflows/dotnet-test.yml@main
    with:
      project_path: ./src
      dotnet-version: 7.0.x

  build-docker-containers:
    name: Build Docker Containers
    needs: build-test
    
    strategy:
      fail-fast: true
      matrix:
        include:
          - image_name: dotnet-sample
            dockerfile: ./src/DotnetSamlpe.Docker/Dockerfile
          - image_name: dotnet-sample-awesome
            dockerfile: ./src/DotnetSample.DockerAwesome/Dockerfile
          
    
    uses: ftoft/shared-workflows/.github/workflows/dotnet-build-test-publish-docker.yml@main
    with:
      project_path: ./src
      dockerfile_path: ${{ matrix.dockerfile }}
      docker_image_name: ${{ matrix.image_name }}
    secrets:
      token: ${{ secrets.token }}
    
    